name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: black_formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Lint
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
